WEATHER_API_KEY=ba3e4e211e1b86198cfd0d785843da62
WEATHER_API_URL=https://api.openweathermap.org/data/2.5/forecast
# MONGODB_USERNAME=your_username_here     
# MONGODB_PASSWORD=your_password_here
DEFAULT_CITY=Hanoi